function out = overlap_frac(fa_path,ims)

im_fa = FiberPlot(fa_path);
im_gt = FiberPlotGT(ims);
bw_fa = rgb2gray(im_fa)~=255;
bw_gt = rgb2gray(im_gt)~=255;

% True positives: # pixels that are 1 in both GT and FA / 
%                   # of pixels that are 1 in GT
true_pos = ...
    sum(sum(...
    bw_gt & bw_fa))...
    / sum(sum(bw_gt));
            
% False positives: # pixels that are 1 in GT but 0 in FA /
%                   # of pixels that are 1 in GT
false_pos = ...
    sum(sum(...
    bw_gt & ~bw_fa...
    )) / sum(sum(bw_gt));

% True negatives: # pixels that are 0 in GT and 0 in FA /
%                   # of pixels that are 0 in GT
true_neg = ...
    sum(sum(...
    ~bw_gt & ~bw_fa...
    )) / sum(sum(~bw_gt));

% False negatives: # pixels that are 0 in GT but 1 in FA /
%                   # of pixels that are 0 in GT
false_neg = ...
    sum(sum(...
    ~bw_gt & bw_fa...
    )) / sum(sum(~bw_gt));

out = [true_pos, false_pos, true_neg, false_neg];

end